version: '3.9'

networks:
  transcendence:
    driver: bridge

services:
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
  database:
    networks: 
      - transcendence
    build: srcs/db
    container_name: db
    image: postgres
    env_file:
        - "./.env"
    restart: "no"
    volumes: 
      - "db:/var/lib/postgressql/data"
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
  back-end:
    networks: 
      - transcendence
    depends_on:
      - database
    build: srcs/back-end
    container_name: back-end
    image: back-end
    ports:
      - "3000:3000"
      - "5555:5555" # prisma studio | A enlever en prod!

    env_file:
      - "./.env"
    restart: "no"

volumes:
  db:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/${HOME}/data/db'